name: streamable_state
description: A simple state management solution made from two classes
version: 1.0.0
homepage: https://github.com/eliseyOzerov/streamable_state

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
